### ISSUE TITLE
Add at lest undersore as allowed character to TAGs names.

### ISSUE THREAD

**Issue by marcinpraczko** [tmrts/boilr#32] opened 2016-09-16 21:12 UTC
Currently boilr is not allowing use one of character `_ -` in tag name. I think that this will be more very helpful.

Examples:

```
# Not easy to read
sometag01
sometag02

# Easier to read
some_tag_01
some_tag_02
```

For example if there is 'testing' template and would be nice to add is with different name (version). So this can help test and approve template before renaming (re importing) with the same tag name.

**Comment by tmrts** [comment] 2017-01-07 15:23
@marcinpraczko `_` and `-` is permitted in the master but not in `0.2.0`, release is outdated that was the cause

**Comment by tmrts** [comment] 2017-02-27 12:56
Fixed in the new release https://github.com/tmrts/boilr/releases/tag/0.3.0

**Closed as completed by tmrts** 2017-02-27 12:56 UTC
Labels: bug
